### ISSUE TITLE
Does it support hooking user-level function addresses?

### ISSUE THREAD

**Issue by romanholidaypancakes** [momo5502/hypervisor#11]
Can you provide an example? I can't find it.

**Comment by momo5502** [comment]
It does: https://github.com/momo5502/hypervisor/blob/main/src/runner/main.cpp#L40

It essentially supports patching the bytes. If you want to hook, you need to insert the appropriate patch bytes (E9, FF 25 or whatever suits your needs) and then redirect the flow to your desired function. note that the hypervisor runner operates in a different process environment. that means you need to inject hyperhook into the desired process and operate from there, or inject a library into the target process, which you can use to redirect the hook to.
